apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
data:
  INTERNAL_API_BASE_URL: "__INTERNAL_API_BASE_URL__"
  GITEA_BASE_URL: "__GITEA_BASE_URL__"
  GITEA_ORG: "__GITEA_ORG__"
  ENV: "__ENV__"
  LOG_LEVEL: "__LOG_LEVEL__"
  NODE_OPTIONS: "--max-old-space-size=1536"
  SPACE_STORAGE_ROOT: "__SPACE_STORAGE_ROOT__"
  SPACE_SYSTEM_ROOT: "__SPACE_SYSTEM_ROOT__"
  CHECKPOINT_CACHE_ROOT: "__CHECKPOINT_CACHE_ROOT__"
  SPACE_STORAGE_SUBPATH: "__SPACE_STORAGE_SUBPATH__"
  CHECKPOINT_CACHE_SUBPATH: "__CHECKPOINT_CACHE_SUBPATH__"
  PLATFORM_CONFIG_ROOT: "__PLATFORM_CONFIG_ROOT__"
  PLATFORM_SPACE_ID: "__PLATFORM_SPACE_ID__"
  CONFIGS_SUBPATH: "__CONFIGS_SUBPATH__"
  TURN_OBJECT_S3_ENDPOINT: "__TURN_OBJECT_S3_ENDPOINT__"
  TURN_OBJECT_S3_REGION: "__TURN_OBJECT_S3_REGION__"
  TURN_OBJECT_S3_BUCKET: "__TURN_OBJECT_S3_BUCKET__"
  PUBLIC_ASSET_OSS_ENDPOINT: "__PUBLIC_ASSET_OSS_ENDPOINT__"
  PUBLIC_ASSET_OSS_REGION: "__PUBLIC_ASSET_OSS_REGION__"
  PUBLIC_ASSET_OSS_BUCKET: "__PUBLIC_ASSET_OSS_BUCKET__"
  CHECKPOINT_ASSET_OSS_ENDPOINT: "__CHECKPOINT_ASSET_OSS_ENDPOINT__"
  CHECKPOINT_ASSET_OSS_REGION: "__CHECKPOINT_ASSET_OSS_REGION__"
  CHECKPOINT_ASSET_OSS_BUCKET: "__CHECKPOINT_ASSET_OSS_BUCKET__"
  TASK_WORKER_SHUTDOWN_TIMEOUT_MS: "__TASK_WORKER_SHUTDOWN_TIMEOUT_MS__"
  SYSTEM_WORKER_SHUTDOWN_TIMEOUT_MS: "__SYSTEM_WORKER_SHUTDOWN_TIMEOUT_MS__"
