CREATE UNIQUE INDEX "v2_uq_labels_id_scope" ON "v2"."labels" USING btree ("id","scope_type","scope_id");--> statement-breakpoint
CREATE UNIQUE INDEX "v2_uq_space_channels_id_space" ON "v2"."space_channels" USING btree ("id","space_id");--> statement-breakpoint
CREATE UNIQUE INDEX "v2_uq_space_sessions_id_space" ON "v2"."space_sessions" USING btree ("id","space_id");--> statement-breakpoint
CREATE UNIQUE INDEX "v2_uq_works_id_space" ON "v2"."works" USING btree ("id","space_id");--> statement-breakpoint
ALTER TABLE "v2"."canvas_checkpoint_snapshots" ADD CONSTRAINT "v2_fk_canvas_checkpoint_snapshots_checkpoint" FOREIGN KEY ("checkpoint_id") REFERENCES "v2"."checkpoints"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."canvas_checkpoint_snapshots" ADD CONSTRAINT "v2_fk_canvas_checkpoint_snapshots_source_document" FOREIGN KEY ("source_document_id") REFERENCES "v2"."canvas_documents"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."canvas_checkpoint_snapshots" ADD CONSTRAINT "v2_fk_canvas_checkpoint_snapshots_source_space" FOREIGN KEY ("source_space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."checkpoints" ADD CONSTRAINT "v2_fk_checkpoints_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."checkpoints" ADD CONSTRAINT "v2_fk_checkpoints_parent" FOREIGN KEY ("parent_checkpoint_id") REFERENCES "v2"."checkpoints"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."checkpoints" ADD CONSTRAINT "v2_fk_checkpoints_root" FOREIGN KEY ("root_checkpoint_id") REFERENCES "v2"."checkpoints"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."cron_jobs" ADD CONSTRAINT "v2_fk_cron_jobs_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE restrict ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."cron_jobs" ADD CONSTRAINT "v2_fk_cron_jobs_session" FOREIGN KEY ("session_id") REFERENCES "v2"."space_sessions"("id") ON DELETE restrict ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."cron_jobs" ADD CONSTRAINT "v2_fk_cron_jobs_session_space" FOREIGN KEY ("session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."label_assignments" ADD CONSTRAINT "v2_fk_label_assignments_label_scope" FOREIGN KEY ("label_id","scope_type","scope_id") REFERENCES "v2"."labels"("id","scope_type","scope_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."labels" ADD CONSTRAINT "v2_fk_labels_parent" FOREIGN KEY ("parent_id") REFERENCES "v2"."labels"("id") ON DELETE restrict ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."proposals" ADD CONSTRAINT "v2_fk_proposals_source_checkpoint" FOREIGN KEY ("source_checkpoint_id") REFERENCES "v2"."checkpoints"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."proposals" ADD CONSTRAINT "v2_fk_proposals_target_space" FOREIGN KEY ("target_space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."provider_message_refs" ADD CONSTRAINT "provider_message_refs_session_message_id_session_messages_id_fk" FOREIGN KEY ("session_message_id") REFERENCES "v2"."session_messages"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."provider_message_refs" ADD CONSTRAINT "v2_fk_provider_message_refs_session_space" FOREIGN KEY ("space_session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."provider_message_refs" ADD CONSTRAINT "v2_fk_provider_message_refs_space_channel" FOREIGN KEY ("space_channel_id") REFERENCES "v2"."space_channels"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."referrals" ADD CONSTRAINT "v2_fk_referrals_referral_code" FOREIGN KEY ("referral_code_id") REFERENCES "v2"."referral_codes"("id") ON DELETE restrict ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."resource_references" ADD CONSTRAINT "v2_fk_resource_references_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."resource_references" ADD CONSTRAINT "v2_fk_resource_references_session" FOREIGN KEY ("session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."resource_references" ADD CONSTRAINT "v2_fk_resource_references_source_turn" FOREIGN KEY ("source_turn_id") REFERENCES "v2"."session_turns"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_forks" ADD CONSTRAINT "session_forks_anchor_turn_id_session_turns_id_fk" FOREIGN KEY ("anchor_turn_id") REFERENCES "v2"."session_turns"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_forks" ADD CONSTRAINT "v2_fk_session_forks_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_forks" ADD CONSTRAINT "v2_fk_session_forks_parent_session" FOREIGN KEY ("parent_session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_forks" ADD CONSTRAINT "v2_fk_session_forks_child_session" FOREIGN KEY ("child_session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_forks" ADD CONSTRAINT "v2_fk_session_forks_root_session" FOREIGN KEY ("root_session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_forks" ADD CONSTRAINT "v2_fk_session_forks_anchor_source_session" FOREIGN KEY ("anchor_source_session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_messages" ADD CONSTRAINT "v2_fk_session_messages_session" FOREIGN KEY ("session_id") REFERENCES "v2"."space_sessions"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_turn_segments" ADD CONSTRAINT "v2_fk_session_turn_segments_session" FOREIGN KEY ("session_id") REFERENCES "v2"."space_sessions"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_turn_segments" ADD CONSTRAINT "v2_fk_session_turn_segments_source_session" FOREIGN KEY ("source_session_id") REFERENCES "v2"."space_sessions"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."session_turns" ADD CONSTRAINT "v2_fk_session_turns_session" FOREIGN KEY ("session_id") REFERENCES "v2"."space_sessions"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_channels" ADD CONSTRAINT "v2_fk_space_channels_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_channels" ADD CONSTRAINT "v2_fk_space_channels_channel" FOREIGN KEY ("channel_id") REFERENCES "v2"."user_channels"("id") ON DELETE restrict ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_commerce_businesses" ADD CONSTRAINT "v2_fk_space_commerce_businesses_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_marks" ADD CONSTRAINT "v2_fk_space_marks_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_members" ADD CONSTRAINT "v2_fk_space_members_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_mods" ADD CONSTRAINT "v2_fk_space_mods_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_mods" ADD CONSTRAINT "v2_fk_space_mods_mod_space" FOREIGN KEY ("mod_space_id") REFERENCES "v2"."spaces"("id") ON DELETE restrict ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_sandboxes" ADD CONSTRAINT "v2_fk_space_sandboxes_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_session_bindings" ADD CONSTRAINT "v2_fk_space_session_bindings_session_space" FOREIGN KEY ("space_session_id","space_id") REFERENCES "v2"."space_sessions"("id","space_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_session_bindings" ADD CONSTRAINT "v2_fk_space_session_bindings_channel_space" FOREIGN KEY ("space_channel_id","space_id") REFERENCES "v2"."space_channels"("id","space_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_sessions" ADD CONSTRAINT "space_sessions_last_message_id_session_messages_id_fk" FOREIGN KEY ("last_message_id") REFERENCES "v2"."session_messages"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."space_sessions" ADD CONSTRAINT "v2_fk_space_sessions_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."spaces" ADD CONSTRAINT "spaces_base_checkpoint_id_checkpoints_id_fk" FOREIGN KEY ("base_checkpoint_id") REFERENCES "v2"."checkpoints"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."spaces" ADD CONSTRAINT "spaces_head_checkpoint_id_checkpoints_id_fk" FOREIGN KEY ("head_checkpoint_id") REFERENCES "v2"."checkpoints"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."task_runs" ADD CONSTRAINT "v2_fk_task_runs_cron_job" FOREIGN KEY ("cron_job_id") REFERENCES "v2"."cron_jobs"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."task_runs" ADD CONSTRAINT "v2_fk_task_runs_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."task_runs" ADD CONSTRAINT "v2_fk_task_runs_session" FOREIGN KEY ("session_id") REFERENCES "v2"."space_sessions"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."task_runs" ADD CONSTRAINT "v2_fk_task_runs_turn" FOREIGN KEY ("turn_id") REFERENCES "v2"."session_turns"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."work_versions" ADD CONSTRAINT "v2_fk_work_versions_work" FOREIGN KEY ("work_id") REFERENCES "v2"."works"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."work_viewer_grants" ADD CONSTRAINT "v2_fk_work_viewer_grants_work_space" FOREIGN KEY ("work_id","space_id") REFERENCES "v2"."works"("id","space_id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."works" ADD CONSTRAINT "works_current_version_id_work_versions_id_fk" FOREIGN KEY ("current_version_id") REFERENCES "v2"."work_versions"("id") ON DELETE set null ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."works" ADD CONSTRAINT "v2_fk_works_space" FOREIGN KEY ("space_id") REFERENCES "v2"."spaces"("id") ON DELETE cascade ON UPDATE no action NOT VALID;--> statement-breakpoint
ALTER TABLE "v2"."cron_jobs" ADD CONSTRAINT "v2_chk_cron_jobs_session_context" CHECK ("v2"."cron_jobs"."session_id" IS NULL OR "v2"."cron_jobs"."space_id" IS NOT NULL) NOT VALID;
