apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
data:
  AUTH_BASE_URL: "__AUTH_BASE_URL__"
  GITEA_BASE_URL: "__GITEA_BASE_URL__"
  GITEA_MANAGED_EMAIL_DOMAIN: "__GITEA_MANAGED_EMAIL_DOMAIN__"
  WEB_ORIGIN: "__WEB_ORIGIN__"
  SANDBOX_AGENT_IMAGE: "__SANDBOX_AGENT_IMAGE__"
  ENV: "__ENV__"
  SPACE_STORAGE_ROOT: "__SPACE_STORAGE_ROOT__"
