import { Hono } from "hono";
import healthRouter from "./health.route.js";
import modelsRouter from "./models.route.js";
import modelsStatusRouter from "./models-status.route.js";
import meRouter from "./me.route.js";
import meLabelsRouter from "./me-labels.route.js";
import channelsRouter from "./channels.route.js";
import spacesRouter from "./spaces/index.js";
import sessionsRouter from "./sessions.route.js";
import sessionAccessRouter from "./session-access.route.js";
import internalRouter from "./internal/index.js";
import cronJobsRouter from "./cron-jobs.route.js";
import tasksRouter from "./tasks.route.js";
import trendingRouter from "./trending.route.js";
import promptsRouter from "./prompts.route.js";
import skillsRouter from "./skills.route.js";
import inviteRouter from "./invite.route.js";
import referralsRouter from "./referrals.route.js";
import searchRouter from "./search.route.js";
import generationsRouter from "./generations.route.js";
import billingRouter from "./billing.route.js";
import queuesRouter from "./queues.route.js";
import publicAssetsRouter from "./public-assets.route.js";
import worksRouter from "./works.route.js";
import workCommerceRouter from "./work-commerce.route.js";
import usersRouter from "./users.route.js";
import referencesRouter from "./references.route.js";
import uiCommandsRouter from "./ui-commands.route.js";
import previewRouter from "./preview.route.js";

const router = new Hono();

router.route("/", healthRouter);
router.route("/api/models/status", modelsStatusRouter);
router.route("/api/models", modelsRouter);
router.route("/api/prompts", promptsRouter);
router.route("/api/skills", skillsRouter);
router.route("/api/me", meRouter);
router.route("/api/me", meLabelsRouter);
router.route("/api/channels", channelsRouter);
router.route("/api/spaces", spacesRouter);
router.route("/api/sessions", sessionsRouter);
router.route("/api/sessions", sessionAccessRouter);
router.route("/api/cron-jobs", cronJobsRouter);
router.route("/api/tasks", tasksRouter);
router.route("/api/trending", trendingRouter);
router.route("/api/invite", inviteRouter);
router.route("/api/referrals", referralsRouter);
router.route("/api/search", searchRouter);
router.route("/api/generations", generationsRouter);
router.route("/api/billing", billingRouter);
router.route("/api/queues", queuesRouter);
router.route("/api/public-assets", publicAssetsRouter);
router.route("/api/works", worksRouter);
router.route("/api", workCommerceRouter);
router.route("/api/users", usersRouter);
router.route("/api/references", referencesRouter);
router.route("/api/ui/commands", uiCommandsRouter);
router.route("/", previewRouter);
router.route("/internal", internalRouter);

export default router;
