export { shouldUseFsCdnForMeta, type FsCdnFileMeta } from "@cohub/space-fs";
import { spaceFsModule } from "./space-fs-module.js";
const cdn = spaceFsModule.cdn;
export const getFsCdnManifest = cdn.getFsCdnManifest;
export const getFreshFsCdnManifests = cdn.getFreshFsCdnManifests;
export const enqueueFsCdnWarmForMeta = cdn.enqueueFsCdnWarmForMeta;
export const waitForFsCdnManifests = cdn.waitForFsCdnManifests;
export const ensureFsCdnManifest = cdn.ensureFsCdnManifest;
export const buildUrlFileResponse = cdn.buildUrlFileResponse;
export const buildPreparingFile = cdn.buildPreparingFile;
export const getFsCdnManifestTtlSeconds = cdn.getFsCdnManifestTtlSeconds;
