export type { SpaceUploadManifestEntry, SpaceUploadDestination, SpaceUploadManifest } from "@cohub/space-fs";
import { spaceFsModule } from "./space-fs-module.js";
const upload = spaceFsModule.upload;
export const createSpaceUploadId = upload.createSpaceUploadId;
export const buildSpaceUploadObjectKey = upload.buildSpaceUploadObjectKey;
export const saveSpaceUploadManifest = upload.saveSpaceUploadManifest;
export const getSpaceUploadManifest = upload.getSpaceUploadManifest;
export const deleteSpaceUploadManifest = upload.deleteSpaceUploadManifest;
export const beginSpaceUploadComplete = upload.beginSpaceUploadComplete;
export const finishSpaceUploadComplete = upload.finishSpaceUploadComplete;
export const cancelSpaceUploadComplete = upload.cancelSpaceUploadComplete;
export const createPresignedPutUrl = upload.createPresignedPutUrl;
export const createInternalPresignedPutUrl = upload.createInternalPresignedPutUrl;
export const createPresignedGetUrl = upload.createPresignedGetUrl;
