export { SpaceFsError, spaceFsJsonError, assertSafeRelativePath, assertInsideRoot, sanitizeFileName, getMimeType, isTextMime, type SpaceFsVisibility } from "@cohub/space-fs";
import { spaceFsModule } from "./space-fs-module.js";
const ops = spaceFsModule.spaceFs;
export const getSpaceRoot = ops.getSpaceRoot;
export const ensureSpaceWorkspaceReady = ops.ensureSpaceWorkspaceReady;
export const listSpaceDirectory = ops.listSpaceDirectory;
export const readSpaceFile = ops.readSpaceFile;
export const readSpaceDirectoryFiles = ops.readSpaceDirectoryFiles;
export const readSpaceFiles = ops.readSpaceFiles;
export const streamSpaceFile = ops.streamSpaceFile;
export const writeSpaceFile = ops.writeSpaceFile;
export const createSpaceFileExclusive = ops.createSpaceFileExclusive;
export const createSpaceDirectory = ops.createSpaceDirectory;
export const deleteSpaceNode = ops.deleteSpaceNode;
export const moveSpaceNode = ops.moveSpaceNode;
export const uploadSpaceFiles = ops.uploadSpaceFiles;
