NAMESPACE: "cohub-dev"
APP_NAME: "cohub-fs-api-dev"

IMAGE_REPOSITORY: "git.talesofai.com/talesofai/cohub-fs-api"
IMAGE_TAG: "latest"
IMAGE_PULL_POLICY: "Always"
IMAGE_PULL_SECRET: "gitea-registry"

SERVICE_PORT: "8789"
CONTAINER_PORT: "8789"

REPLICAS: "1"
REQUEST_CPU: "200m"
REQUEST_MEMORY: "128Mi"
LIMIT_CPU: "1000m"
LIMIT_MEMORY: "512Mi"

LIVENESS_PATH: "/healthz"
LIVENESS_INITIAL_DELAY: "10"
LIVENESS_PERIOD: "10"
LIVENESS_TIMEOUT: "2"
LIVENESS_FAILURE_THRESHOLD: "3"
READINESS_PATH: "/readyz"
READINESS_INITIAL_DELAY: "5"
READINESS_PERIOD: "5"
READINESS_TIMEOUT: "2"
READINESS_FAILURE_THRESHOLD: "3"

LOGTO_ENDPOINT: "https://auth.neta.art"
SPACE_STORAGE_ROOT: "/space-storage"
SPACE_SYSTEM_ROOT: "/system-storage"
SPACE_STORAGE_PVC: "cohub-spaces-pvc"
SPACE_SYSTEM_PVC: "cohub-system-pvc"
SPACE_STORAGE_SUBPATH: "workspaces/dev"
SPACE_SYSTEM_SUBPATH: "dev"

TURN_OBJECT_S3_ENDPOINT: "https://oss-us-west-1-internal.aliyuncs.com"
TURN_OBJECT_S3_REGION: "us-west-1"
TURN_OBJECT_S3_BUCKET: "cohub-sessions"
TURN_OBJECT_CDN_BASE_URL: "https://sessions.cohub.run"

ROUTE_ENABLED: "false"
API_HOSTNAME: "api-dev.cohub.run"

ENV: "dev"
LOG_LEVEL: "debug"
MAX_UNAVAILABLE: "1"
MAX_SURGE: "1"
TERMINATION_GRACE_PERIOD_SECONDS: "60"
